services:
  - type: cron
    name: reddit-trend-detector
    env: python
    buildCommand: pip install -r requirements.txt
    schedule: "*/10 * * * *"
    command: python main.py
    envVars:
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: DISCORD_WEBHOOK
        sync: false
      - key: MIN_VELOCITY
        value: 1000